---
_hotel_id: BOS936
_portal_id: ''
latitude: 42.3486
longitude: -71.09792
name: Boston Hotel Buckminster
email: ''
phone_number: "--"
address:
  street1: 645 Beacon St
  street2: ''
  state: Massachusetts
  city: Boston
  country: United States
  zip_code: '02215'
